version: '3.6'

services:

  userme:
    build: .
    image: flaviostutz/simple-file-server
    ports:
      - "4000:4000"
    environment:
      - LOG_LEVEL=debug
      - DB_DIALECT=sqlite
      # - DB_HOST=mysql
      # - DB_PORT=3306
      # - DB_USERNAME=userme
      # - DB_PASSWORD=userme
      # - DB_NAME=userme
      # - MAIL_SMTP_HOST          'smtp.mailgun.com'
      # - MAIL_SMTP_PORT          '465'
      # - MAIL_SMTP_USER          ''
      # - MAIL_SMTP_PASS          ''
      # - MAIL_FROM_ADDRESS       ''
      # - MAIL_ACTIVATION_SUBJECT ''
      # - MAIL_ACTIVATION_HTML    ''
      # - MAIL_PASSWORD_RESET_SUBJECT 'Password reset requested at Test.com'
      # - MAIL_PASSWORD_RESET_HTML ''
      # - CORS_ALLOWED_ORIGINS             '*'
      # - ACCESS_TOKEN_EXPIRATION_MINUTES  '480'
      # - REFRESH_TOKEN_EXPIRATION_MINUTES '40320'
      # - ACCESS_TOKEN_DEFAULT_SCOPE       'basic'
      # - MAX_INCORRECT_PASSWORD_RETRIES   '5'
      # - ACCOUNT_ACTIVATION_METHOD        'direct'
      # - PASSWORD_VALIDATION_REGEX         ^.{6,30}$
      # - JWT_PRIVATE_KEY_FILE             '/secrets/jwt-private-key'
      # - MASTER_PUBLIC_KEY_FILE            '/secrests/master-public-key'
      
