version: '3.6'

services:

  userme:
    build: .
    image: stutzlab/userme
    ports:
      - "7000:7000"
    restart: always
    environment:
      - LOG_LEVEL=debug
      - DB_DIALECT=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=userme
      - DB_PASSWORD=userme
      - DB_NAME=userme
      - MAIL_SMTP_HOST=mailslurper
      - MAIL_SMTP_PORT=2500
      - MAIL_SMTP_USER=test
      - MAIL_SMTP_PASS=test
      # - MAIL_SMTP_HOST=smtp.mailtrap.io
      # - MAIL_SMTP_PORT=2525
      # - MAIL_SMTP_USER=d999da469e2965
      # - MAIL_SMTP_PASS=0e62129c398c1c
      - MAIL_FROM_NAME=Berimbal
      - MAIL_FROM_ADDRESS=e7a3b40037-7cbde1@inbox.mailtrap.io
      - MAIL_ACTIVATION_SUBJECT=Activate your account at Berimbau.com!
      - MAIL_ACTIVATION_HTML=<b>Hi DISPLAY_NAME</b>, <p> <a href="http://test.com/account-activate.html?t=ACTIVATION_TOKEN">Click here to complete your registration</a><p>http://test.com/account-activate.html?t=ACTIVATION_TOKEN</p><br>Be welcome!</p> <p>-Test Team.</p>
      - MAIL_PASSWORD_RESET_SUBJECT=Password reset requested at Berimbau.com
      - MAIL_PASSWORD_RESET_HTML=<b>Hi DISPLAY_NAME</b>, <p> <a href="http://test.com/reset-password.html?t=PASSWORD_RESET_TOKEN">Click here to reset your password</a></p><p>http://test.com/reset-password.html?t=PASSWORD_RESET_TOKEN</p><p>-Test Team.</p>
      - MAIL_TOKENS_FOR_TESTS=true
      - ACCOUNT_ACTIVATION_METHOD=mail
      # - CORS_ALLOWED_ORIGINS             '*'
      # - ACCESS_TOKEN_EXPIRATION_MINUTES  '480'
      # - REFRESH_TOKEN_EXPIRATION_MINUTES '40320'
      #- VALIDATION_TOKEN_EXPIRATION_MINUTES=10
      # - ACCESS_TOKEN_DEFAULT_SCOPE       'basic'
      # - MAX_INCORRECT_PASSWORD_RETRIES   '5'
      # - PASSWORD_VALIDATION_REGEX         ^.{6,30}$
      # - PASSWORD_EXPIRATION_DAYS=1
      # - FACEBOOK_CLIENT_ID
      # - FACEBOOK_CLIENT_SECRET
      - JWT_SIGNING_METHOD=ES256
      # - JWT_SIGNING_KEY_FILE=/run/secrets/jwt-private-key
      # - MASTER_PUBLIC_KEY_FILE            '/secrests/master-public-key'
      - FACEBOOK_CLIENT_ID=884133135440365
      - FACEBOOK_CLIENT_SECRET=
      - GOOGLE_CLIENT_ID=339086941381-61h3t55u99n9rt0arqmu655cvs3gk3ol.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=
    secrets:
      - jwt-signing-key

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=userme
      - MYSQL_USER=userme
      - MYSQL_PASSWORD=userme
      - MYSQL_DATABASE=userme
    volumes: 
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer:4.7.6
    restart: always
    ports:
      - "8282:8080"

  mailslurper:
    image: marcopas/docker-mailslurper
    ports:
      - "8080:8080"
      - "8085:8085"
      - "2500:2500"
    restart: always

secrets:
  jwt-signing-key:
    file: ./tests/test-key.pem

volumes:
  mysql-data:
